# Generated by Django 3.0.8 on 2021-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praye',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='YOUR FULLNAME', max_length=489)),
                ('residential', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('church', models.CharField(max_length=333)),
                ('city', models.CharField(max_length=100)),
                ('call', models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Will You Want a Call Back?')),
                ('pray_for', models.CharField(choices=[('Myself', 'Myself'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Friend', 'Friend'), ('Sibling', 'Siblings')], max_length=8, verbose_name='This prayer is for')),
                ('prayer', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Prayer',
        ),
    ]
