# Generated by Django 3.0.8 on 2021-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_auto_20210923_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=125)),
                ('residence', models.CharField(max_length=678)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('born_again', models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=3)),
                ('church', models.CharField(max_length=333)),
                ('date_of_new_birth', models.DateField()),
                ('instrument', models.CharField(max_length=58)),
                ('foundation_class', models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=22)),
                ('part_sing', models.CharField(choices=[('Sop', 'soprano'), ('Alt', 'Alto'), ('Ten', 'Tenor'), ('ND', 'No Idea')], max_length=15)),
                ('marital_status', models.CharField(choices=[('MAR', 'MARRIED'), ('SING', 'SINGLE'), ('WID', 'WIDOWED'), ('SEPA', 'SEPARATED'), ('DIV', 'DIVORCE')], max_length=15)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
