# Generated by Django 3.0.8 on 2021-09-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0003_choir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='church',
            field=models.DateField(),
        ),
    ]
