# Generated by Django 3.0.8 on 2021-09-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_auto_20210924_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
