# Generated by Django 3.0.8 on 2021-09-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0005_auto_20210924_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshop',
            options={'verbose_name_plural': 'DOMINION BOOKSHOP'},
        ),
        migrations.AlterModelOptions(
            name='choir',
            options={'verbose_name_plural': 'CHOIR'},
        ),
        migrations.AlterModelOptions(
            name='counsel',
            options={'verbose_name_plural': 'COUNSELLING'},
        ),
        migrations.AlterModelOptions(
            name='praye',
            options={'verbose_name_plural': 'PRAYER REQUEST'},
        ),
        migrations.AlterField(
            model_name='choir',
            name='born_again',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='choir',
            name='foundation_class',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='choir',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('WIDOWED', 'WIDOWED'), ('SEPARATED', 'SEPARATED'), ('DIVORCED', 'DIVORCED')], max_length=9),
        ),
        migrations.AlterField(
            model_name='choir',
            name='part_sing',
            field=models.CharField(choices=[('soprano', 'soprano'), ('Alto', 'Alto'), ('Tenor', 'Tenor'), ('No Idea', 'No Idea')], max_length=7),
        ),
    ]
