# Generated by Django 3.0.8 on 2021-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0007_auto_20210924_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='born_again',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='choir',
            name='foundation_class',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No'), ('why Should I', 'why Should I')], max_length=15),
        ),
        migrations.AlterField(
            model_name='security',
            name='foundation_class',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('why Should I', 'why Should I')], max_length=15),
        ),
    ]
