# Generated by Django 3.0.8 on 2021-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0009_auto_20210924_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='job',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Shift', 'Shift'), ('Sunday', 'Sunday')], max_length=7),
        ),
    ]
