# Generated by Django 3.0.8 on 2021-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0014_auto_20210926_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROPHETIC_FOCUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='prophetic/month')),
                ('month', models.CharField(max_length=345)),
                ('year', models.BigIntegerField()),
                ('theme', models.CharField(max_length=345)),
                ('reference', models.CharField(max_length=202)),
                ('body', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'PROPHETIC FOCUS',
            },
        ),
    ]
