# Generated by Django 3.0.8 on 2021-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0016_auto_20210926_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prophet_focus',
            name='body',
            field=models.TextField(),
        ),
    ]
