# Generated by Django 3.0.8 on 2021-09-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0018_author_books_of_the_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
