# Generated by Django 3.0.8 on 2021-09-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0020_auto_20210927_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=890)),
            ],
        ),
    ]
