# Generated by Django 3.0.8 on 2021-09-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0021_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterField(
            model_name='books_of_the_months',
            name='book_1',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='books_of_the_months',
            name='book_2',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
