# Generated by Django 3.0.8 on 2021-09-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0022_auto_20210927_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_of_the_months',
            old_name='book_1',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='books_of_the_months',
            name='book_2',
        ),
        migrations.RemoveField(
            model_name='books_of_the_months',
            name='book_3',
        ),
        migrations.RemoveField(
            model_name='books_of_the_months',
            name='book_4',
        ),
        migrations.RemoveField(
            model_name='books_of_the_months',
            name='book_5',
        ),
    ]
