# Generated by Django 3.0.8 on 2021-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0024_recommended_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=333)),
                ('centre', models.CharField(max_length=666)),
                ('residence', models.CharField(max_length=999)),
                ('Host', models.CharField(max_length=777)),
                ('minister', models.CharField(max_length=888)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'WSF',
            },
        ),
    ]
