# Generated by Django 3.0.8 on 2021-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0026_auto_20210928_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_title',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
