# Generated by Django 3.0.8 on 2021-09-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0027_auto_20210928_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_graduate',
            new_name='bcc_graduate',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_graduate_remark',
            new_name='bcc_graduate_remark',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_graduate_sup',
            new_name='bcc_graduate_sup',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_orient',
            new_name='bcc_orient',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_orient_remark',
            new_name='bcc_orient_remark',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_orient_sup',
            new_name='bcc_orient_sup',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_resume',
            new_name='bcc_resume',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_resume_remark',
            new_name='bcc_resume_remark',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_resume_sup',
            new_name='bcc_resume_sup',
        ),
        migrations.RenameField(
            model_name='wofbi',
            old_name='bbc_sp_dt',
            new_name='bcc_title',
        ),
        migrations.RemoveField(
            model_name='wofbi',
            name='bbc_sp_sup',
        ),
        migrations.RemoveField(
            model_name='wofbi',
            name='bbc_st_dt',
        ),
        migrations.RemoveField(
            model_name='wofbi',
            name='bbc_st_sup',
        ),
        migrations.RemoveField(
            model_name='wofbi',
            name='bbc_title',
        ),
        migrations.AddField(
            model_name='wofbi',
            name='bcc_sp_dt',
            field=models.CharField(default='SPECIAL', max_length=99, verbose_name='BCC (STOP DATE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wofbi',
            name='bcc_sp_sup',
            field=models.CharField(default='SPECIAL', max_length=4, verbose_name='BCC (e.g th, nd, st)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wofbi',
            name='bcc_st_dt',
            field=models.CharField(default='SPECIAL', max_length=99, verbose_name='BCC (START DATE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wofbi',
            name='bcc_st_sup',
            field=models.CharField(default='SPECIAL', max_length=4, verbose_name='BCC (e.g th, nd, st)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_sp_dt',
            field=models.CharField(max_length=99, verbose_name='JBS (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_st_dt',
            field=models.CharField(max_length=99, verbose_name='JBS (START DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_sp_dt',
            field=models.CharField(max_length=99, verbose_name='LCC (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_st_dt',
            field=models.CharField(max_length=99, verbose_name='LCC (START DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_sp_dt',
            field=models.CharField(max_length=99, verbose_name='LDC (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_st_dt',
            field=models.CharField(max_length=99, verbose_name='LDC (START DATE)'),
        ),
    ]
