# Generated by Django 3.0.8 on 2021-09-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0028_auto_20210928_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_graduate',
            field=models.CharField(max_length=222, verbose_name='JBS Graduation Date'),
        ),
    ]
