# Generated by Django 3.0.8 on 2021-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0030_auto_20210928_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_graduate',
            field=models.CharField(blank=True, max_length=222, verbose_name='BBC Graduation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_graduate_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='BBC Graduation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_graduate_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='BBC Graduation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_orient',
            field=models.CharField(blank=True, max_length=222, verbose_name='BASIC CERTIFICATE COURSE (BBC) Orientation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_orient_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='BBC Orientation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_orient_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='BBC Orientation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_resume',
            field=models.CharField(blank=True, max_length=222, verbose_name='BBC Resumption Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_resume_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='BBC Resumption Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_resume_sup',
            field=models.CharField(blank=True, max_length=6, verbose_name='BBC Resumption (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_sp_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='BCC (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_sp_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='BCC (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_st_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='BCC (START DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_st_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='BCC (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='bcc_title',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_graduate',
            field=models.CharField(blank=True, max_length=222, verbose_name='JBS Graduation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_graduate_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='JBS Graduation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_graduate_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='JBS Graduation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_orient',
            field=models.CharField(blank=True, max_length=222, verbose_name='JUNIOR BIBLE SCHOOL (JBS) Orientation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_orient_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='JBS Orientation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_orient_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='JBS Orientation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_resume',
            field=models.CharField(blank=True, max_length=222, verbose_name='JBS Resumption Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_resume_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='JBS Resumption Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_resume_sup',
            field=models.CharField(blank=True, max_length=6, verbose_name='JBS Resumption (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_sp_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='JBS (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_sp_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='JBS (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_st_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='JBS (START DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='jbs_st_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='JBS (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_graduate',
            field=models.CharField(blank=True, max_length=222, verbose_name='LCC Graduation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_graduate_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='LCC Graduation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_graduate_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='LCC Graduation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_orient',
            field=models.CharField(blank=True, max_length=222, verbose_name='LEADERSHIP CERTIFICATE COURSE (LCC) Orientation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_orient_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='LCC Orientation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_orient_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='LCC Orientation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_resume',
            field=models.CharField(blank=True, max_length=222, verbose_name='LCC Resumption Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_resume_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='LCC Resumption Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_resume_sup',
            field=models.CharField(blank=True, max_length=6, verbose_name='LCC Resumption (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_sp_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='LCC (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_sp_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='LCC (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_st_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='LCC (START DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_st_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='LCC (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='lcc_title',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_graduate',
            field=models.CharField(blank=True, max_length=222, verbose_name='LDC Graduation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_graduate_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='LDC Graduation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_graduate_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='LDC Graduation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_orient',
            field=models.CharField(blank=True, max_length=222, verbose_name='LEADERSHIP DIPLOMA COURSE (LDC) Orientation Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_orient_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='LDC Orientation Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_orient_sup',
            field=models.CharField(blank=True, max_length=5, verbose_name='LDC Orientation (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_resume',
            field=models.CharField(blank=True, max_length=222, verbose_name='LDC Resumption Date'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_resume_remark',
            field=models.CharField(blank=True, max_length=222, verbose_name='LDC Resumption Remark'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_resume_sup',
            field=models.CharField(blank=True, max_length=6, verbose_name='LDC Resumption (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_sp_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='LDC (STOP DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_sp_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='LDC (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_st_dt',
            field=models.CharField(blank=True, max_length=99, verbose_name='LDC (START DATE)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_st_sup',
            field=models.CharField(blank=True, max_length=4, verbose_name='LDC (e.g th, nd, st)'),
        ),
        migrations.AlterField(
            model_name='wofbi',
            name='ldc_title',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
