# Generated by Django 3.0.8 on 2021-09-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0031_auto_20210928_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sp_Wk_Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='spiritual/week')),
                ('m_y', models.CharField(max_length=798, verbose_name='MONTH & YEAR')),
                ('start', models.CharField(max_length=700, verbose_name='STARTING DATE')),
                ('end', models.CharField(max_length=700, verbose_name='ENDING DATE')),
                ('year', models.CharField(max_length=700, verbose_name='YEAR')),
                ('remark_1', models.CharField(blank=True, max_length=999, verbose_name='SHORT COMMENT')),
                ('remark_2', models.CharField(blank=True, max_length=999, verbose_name='THEME OF THE YEAR')),
            ],
            options={
                'verbose_name_plural': 'SPIRITUAL WEEK OF EMPHASIS',
            },
        ),
    ]
