# Generated by Django 3.0.8 on 2021-09-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0032_sp_wk_emp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sp_Wk_Emp',
            new_name='SPIRITUAL',
        ),
    ]
