# Generated by Django 3.0.8 on 2021-09-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0034_auto_20210929_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended_Books_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=17, null=True)),
                ('year', models.CharField(max_length=17, null=True)),
            ],
            options={
                'verbose_name_plural': ' RECOMMENDED BOOKS MONTH and YEAR',
            },
        ),
        migrations.RemoveField(
            model_name='recommended_books',
            name='month',
        ),
        migrations.RemoveField(
            model_name='recommended_books',
            name='year',
        ),
    ]
