# Generated by Django 3.0.8 on 2021-10-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0038_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
