# Generated by Django 3.0.8 on 2021-10-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0039_auto_20211003_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='url',
            field=models.CharField(blank=True, max_length=345),
        ),
    ]
