# Generated by Django 3.0.8 on 2021-10-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0040_auto_20211003_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
