# Generated by Django 3.0.8 on 2021-10-03 20:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0041_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='test')),
                ('d', models.CharField(max_length=4, verbose_name='Day')),
                ('m', models.CharField(max_length=15, verbose_name='Month')),
                ('y', models.CharField(max_length=4, verbose_name='Year')),
                ('Theme', models.CharField(max_length=678)),
                ('Theme_reference', models.CharField(max_length=899)),
                ('message', ckeditor.fields.RichTextField(verbose_name='MESSAGE')),
            ],
        ),
    ]
