# Generated by Django 3.0.8 on 2021-10-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0044_sunday_img_pst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunday',
            name='img_pst',
            field=models.ImageField(upload_to='test', verbose_name='PASTOR PICTURE'),
        ),
    ]
