# Generated by Django 3.0.8 on 2021-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0045_auto_20211003_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunday',
            name='sup',
            field=models.CharField(default='th', max_length=2, verbose_name='e.g st, nd, rd, th '),
            preserve_default=False,
        ),
    ]
