# Generated by Django 3.0.8 on 2021-12-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0048_auto_20211007_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('videofile', models.FileField(null=True, upload_to='Videos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'SERVICE'},
        ),
    ]
