# Generated by Django 3.0.8 on 2021-12-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0049_auto_20211209_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='Videos/messages'),
        ),
    ]
