# Generated by Django 4.0 on 2022-02-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0055_chcaro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home/choir')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
