# Generated by Django 4.0 on 2022-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0056_choirpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirPage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home/choir')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CHOIR SECOND CAROUSEL',
            },
        ),
        migrations.RenameModel(
            old_name='ChoirPage',
            new_name='ChoirPage1',
        ),
        migrations.AlterModelOptions(
            name='choirpage1',
            options={'verbose_name_plural': 'CHOIR CAROUSEL'},
        ),
    ]
