# Generated by Django 4.0 on 2022-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0057_choirpage2_rename_choirpage_choirpage1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home/carousel')),
            ],
            options={
                'verbose_name_plural': 'CHURCH HOME PICTURES',
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
    ]
