# Generated by Django 4.0 on 2022-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0058_homecarousel_remove_services_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('song', models.FileField(upload_to='choir/song')),
            ],
        ),
        migrations.AlterModelOptions(
            name='choirpage2',
            options={'verbose_name_plural': 'CHOIR SIDE CAROUSEL'},
        ),
    ]
