# Generated by Django 4.0 on 2022-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0059_choirsong_alter_choirpage2_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choirsong',
            options={'verbose_name_plural': 'CHOIR SONG'},
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='title',
            field=models.CharField(default='judah', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='img',
            field=models.ImageField(default='judah', upload_to='home/carousel'),
        ),
    ]
