# Generated by Django 4.0 on 2022-05-15 04:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0062_ca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ca',
            options={'verbose_name_plural': 'CHURCH ACCOUNTANT'},
        ),
        migrations.AlterField(
            model_name='ca',
            name='scr',
            field=ckeditor.fields.RichTextField(verbose_name='SCRIPTURE'),
        ),
    ]
