# Generated by Django 3.2 on 2022-06-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0063_alter_ca_options_alter_ca_scr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chcaro',
        ),
    ]
