# Generated by Django 3.2 on 2022-06-27 02:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0064_auto_20220627_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor_Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=333)),
                ('name', models.CharField(max_length=200)),
                ('week', models.CharField(max_length=555)),
                ('scripture', models.CharField(max_length=1000)),
                ('scripture_reference', models.CharField(max_length=190)),
                ('message', ckeditor.fields.RichTextField()),
                ('designation', models.CharField(max_length=345)),
                ('presenter', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'PASTORS DESK',
            },
        ),
    ]
