# Generated by Django 3.2 on 2022-06-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0065_pastor_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastor_desk',
            name='bible_version',
            field=models.CharField(default='KJV', max_length=234),
        ),
    ]
