# Generated by Django 3.2 on 2022-06-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0066_pastor_desk_bible_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='prophet_focus',
            name='book',
            field=models.CharField(default='breakthrough', max_length=789, verbose_name='BOOKS_of_the_Months'),
            preserve_default=False,
        ),
    ]
