# Generated by Django 3.2 on 2022-06-27 04:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0067_prophet_focus_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prophet_focus',
            name='book',
            field=ckeditor.fields.RichTextField(verbose_name='BOOKS_of_the_Months'),
        ),
    ]
